package de.ipk_gatersleben.bit.bi.isa4j.components;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.PipedInputStream;
import java.io.PipedOutputStream;
import java.io.StringReader;
import java.util.ArrayList;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import de.ipk_gatersleben.bit.bi.isa4j.constants.Symbol;

public class StudyTest {
	
	Study study;
	
	@BeforeEach
	void resetStudy() {
		this.study = new Study("Study ID","s_study.txt");
	}
	
	@Test
	void testDirectToStream() throws IOException {
		OutputStream os = new PipedOutputStream(new PipedInputStream());
		OutputStream os2 = new ByteArrayOutputStream();
		// Complain when trying to write to a stream while another is still opened
		study.directToStream(os);
		assertThrows(IllegalStateException.class, () -> study.directToStream(os2));
		// Make it work fine when the first is released
		study.releaseStream();
		study.directToStream(os2);
		// Make sure the first stream is still writable (i.e. it wasn't closed)
		String output = "Hello";
		os.write(output.getBytes());
	}
	
	@Test
	void testWriteHeadersFromExample() throws IOException {
		Source source = new Source("Source Name");
		source.addCharacteristic(new Characteristic("Beauty", new OntologyAnnotation("Very Beautiful")));
		source.addCharacteristic(new Characteristic("Size", new OntologyAnnotation("m", "accession", new Ontology("Ontology", null, null, null))));
		
		Sample sample = new Sample("Sample Name");
		sample.addCharacteristic(new Characteristic("Beauty", new OntologyAnnotation("Very Beautiful")));
		
		Process process = new Process(new Protocol("ProtocolName"));
		process.setInput(source);
		process.setOutput(sample);
		
		// Complain if there's no stream to write to
		assertThrows(IllegalStateException.class, () -> study.writeHeadersFromExample(source));
		
		OutputStream os = new ByteArrayOutputStream();
		study.directToStream(os);
		study.writeHeadersFromExample(source);
		study.releaseStream();
		
		assertEquals(
			"Source Name" + Symbol.TAB + "Characteristics[Beauty]" + Symbol.TAB + "Characteristics[Size]" + Symbol.TAB + "Term Source REF" + Symbol.TAB + "Term Accession Number"
		  + Symbol.TAB + "Protocol REF" 
		  + Symbol.TAB + "Sample Name" + Symbol.TAB + "Characteristics[Beauty]"
		  + Symbol.ENTER,
		  os.toString()
		);
	}
	
	@Test
	void testWriteLine() throws IOException {
		Source source1 = new Source("Source Name");
		Characteristic characteristic1 = new Characteristic("Characteristic", new OntologyAnnotation("Value"));
		source1.addCharacteristic(characteristic1);
		Sample sample1 = new Sample("Sample Name");
		Process process1 = new Process(new Protocol("Watering"));
		process1.setInput(source1);
		process1.setOutput(sample1);
		
		// Complain if there's no stream to write to
		assertThrows(IllegalStateException.class, () -> study.writeLine(source1));
		
		ByteArrayOutputStream os1   = new ByteArrayOutputStream();
    	this.study.directToStream(os1);
    	// Complain if headers were not written yet
    	assertThrows(IllegalStateException.class, () -> study.writeLine(source1));
    	
    	this.study.writeHeadersFromExample(source1);
    	
    	// Complain if elements are missing that are present in the header
    	process1.setOutput(null);
    	assertThrows(NullPointerException.class, () -> this.study.writeLine(source1));
    	
    	// Complain if a group suddenly has more columns than defined in the header (the Characteristic now gets a Term Accession Number for which there is no header)
    	characteristic1.setValue(new OntologyAnnotation("Value","Term Accession",new Ontology("Ontology", null, null, null)));
    	assertThrows(IllegalStateException.class, () -> this.study.writeLine(source1));
    	
    	this.study.releaseStream();
		
		// Like in the investigation tests, compare our output to one generated by python isatools
    	BufferedReader correctFile = new BufferedReader(new InputStreamReader(this.getClass().getResourceAsStream("python_originals/s_study.txt")));
    	ByteArrayOutputStream os   = new ByteArrayOutputStream();
    	this.study.directToStream(os);
    	
    	Protocol protocol1 = new Protocol("foobar Protocol");
    	for(int i = 1; i < 6; i++) {
    		Source source = new Source("Source no. " + i);
    		Sample sample = new Sample("Sample no. " + i);
    		Process process = new Process(protocol1);
    		
    		process.setInput(source);
    		process.setOutput(sample);
    		
    		if(!study.hasWrittenHeaders())
    			study.writeHeadersFromExample(source);
    		study.writeLine(source);
    	}
    	
    	this.study.releaseStream();
    	
    	BufferedReader ourFile	   = new BufferedReader(new StringReader(os.toString()));
    	
    	String correctLine = null;
    	String ourLine	   = null;
    	while((correctLine = correctFile.readLine()) != null && (ourLine = ourFile.readLine()) != null) {
    		assertEquals(correctLine, ourLine);
    	}
    	// Assert that both files are finished here as well
    	assertNull(ourFile.readLine());
    	assertNull(correctFile.readLine());
	}

}
