remote_theme: pmarsceill/just-the-docs
aux_links:
  "isa4j on GitHub":
    - "https://github.com/IPK-BIT/isa4j"

footer_content: "Copyright &copy; Leibniz Institute of Plant Genetics and Crop Plant Research (IPK), Gatersleben, Germany. All rights reserved. This program and the accompanying materials are made available under the terms of the <a href=\"https://spdx.org/licenses/MIT.html\">MIT license</a>"
